name: Check merge requirements

on:
  pull_request: ~

jobs:
  pre-commit:
    name: Prepare pre-commit base
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          check-latest: true
      - name: Create Python virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          python --version
          pip install uv
          uv pip install -r requirements.txt
      - name: Install pre-commit dependencies
        run: |
          . venv/bin/activate
          pre-commit install-hooks
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - '**/*.py'
            mapping_yaml:
              - 'mapping.yaml'
            icons:
              - 'icons_linux/**'
      - name: Run ruff-format
        if: steps.filter.outputs.python == 'true'
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual ruff-format --all-files --show-diff-on-failure
        env:
          RUFF_OUTPUT_FORMAT: github
      - name: Run ruff
        if: steps.filter.outputs.python == 'true'
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual ruff --all-files --show-diff-on-failure
        env:
          RUFF_OUTPUT_FORMAT: github
      - name: Validate mapping
        if: steps.filter.outputs.mapping_yaml == 'true'
        run: |
          . venv/bin/activate
          pre-commit run --hook-stage manual validate_mapping
